const STORAGE_KEY = 'relieflink_registrations';
const SEEDED_KEY = 'relieflink_seeded';

function makeTime(minutesAgo) {
    return new Date(Date.now() - minutesAgo * 60000).toISOString();
}

const SEED_REGISTRATIONS = [
    {
        id: 'RL-00001001-1001',
        name: 'Rajan K',
        village: 'Mundakkai',
        camp: 'Meppadi Relief Camp',
        familyCount: 4,
        injured: false,
        injuryDescription: '',
        trapped: true,
        trappedDescription: 'my brother is near the Mundakkai church, could not cross the valley',
        needs: [],
        timestamp: makeTime(120),
    },
    {
        id: 'RL-00001002-1002',
        name: 'Latha Suresh',
        village: 'Mundakkai',
        camp: 'Meppadi Relief Camp',
        familyCount: 2,
        injured: true,
        injuryDescription: 'leg fracture',
        trapped: true,
        trappedDescription: 'two neighbors stuck near the church in Mundakkai valley',
        needs: [],
        timestamp: makeTime(110),
    },
    {
        id: 'RL-00001003-1003',
        name: 'Biju Thomas',
        village: 'Chooralmala',
        camp: 'Chooralmala School Camp',
        familyCount: 3,
        injured: false,
        injuryDescription: '',
        trapped: false,
        trappedDescription: '',
        needs: ['MEDICINE'],
        timestamp: makeTime(100),
    },
    {
        id: 'RL-00001004-1004',
        name: 'Anitha Ravi',
        village: 'Vellarimala',
        camp: 'Meppadi Relief Camp',
        familyCount: 1,
        injured: false,
        injuryDescription: '',
        trapped: true,
        trappedDescription: 'husband near Mundakkai valley bridge, cannot cross',
        needs: [],
        timestamp: makeTime(90),
    },
    {
        id: 'RL-00001005-1005',
        name: 'Suresh Kumar',
        village: 'Mananthavady',
        camp: 'Mananthavady Town Camp',
        familyCount: 5,
        injured: false,
        injuryDescription: '',
        trapped: false,
        trappedDescription: '',
        needs: ['FOOD', 'WATER'],
        timestamp: makeTime(80),
    },
    {
        id: 'RL-00001006-1006',
        name: 'Mary Joseph',
        village: 'Chooralmala',
        camp: 'Chooralmala School Camp',
        familyCount: 2,
        injured: true,
        injuryDescription: 'head injury — MEDICAL EMERGENCY',
        trapped: false,
        trappedDescription: '',
        needs: ['MEDICINE'],
        timestamp: makeTime(70),
    },
    {
        id: 'RL-00001007-1007',
        name: 'Pradeep Nair',
        village: 'Kalpetta',
        camp: 'Kalpetta Government Camp',
        familyCount: 4,
        injured: false,
        injuryDescription: '',
        trapped: false,
        trappedDescription: '',
        needs: [],
        timestamp: makeTime(55),
    },
    {
        id: 'RL-00001008-1008',
        name: 'Suma Krishnan',
        village: 'Vellarimala',
        camp: 'Meppadi Relief Camp',
        familyCount: 3,
        injured: false,
        injuryDescription: '',
        trapped: true,
        trappedDescription: 'elderly woman still in house near the valley road Mundakkai',
        needs: [],
        timestamp: makeTime(45),
    },
    {
        id: 'RL-00001009-1009',
        name: 'Arun Mohan',
        village: 'Mananthavady',
        camp: 'Mananthavady Town Camp',
        familyCount: 2,
        injured: false,
        injuryDescription: '',
        trapped: false,
        trappedDescription: '',
        needs: ['FOOD'],
        timestamp: makeTime(35),
    },
    {
        id: 'RL-00001010-1010',
        name: 'Thankam Varghese',
        village: 'Sulthan Bathery',
        camp: 'Sulthan Bathery Camp',
        familyCount: 6,
        injured: false,
        injuryDescription: '',
        trapped: false,
        trappedDescription: '',
        needs: ['SHELTER'],
        timestamp: makeTime(25),
    },
    {
        id: 'RL-00001011-1011',
        name: 'Vineeth P',
        village: 'Chooralmala',
        camp: 'Chooralmala School Camp',
        familyCount: 1,
        injured: false,
        injuryDescription: '',
        trapped: true,
        trappedDescription: 'father near the Mananthavady bridge road',
        needs: [],
        timestamp: makeTime(15),
    },
    {
        id: 'RL-00001012-1012',
        name: 'Rekha Babu',
        village: 'Kalpetta',
        camp: 'Kalpetta Government Camp',
        familyCount: 3,
        injured: false,
        injuryDescription: '',
        trapped: false,
        trappedDescription: '',
        needs: ['WATER', 'MEDICINE'],
        timestamp: makeTime(5),
    },
];

export function seedIfEmpty() {
    const seeded = localStorage.getItem(SEEDED_KEY);
    if (!seeded) {
        const existing = localStorage.getItem(STORAGE_KEY);
        if (!existing || JSON.parse(existing).length === 0) {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(SEED_REGISTRATIONS));
        }
        localStorage.setItem(SEEDED_KEY, 'true');
    }
}
